### ISSUE TITLE
Can we have some test cases for each problem?

### ISSUE THREAD

**Issue by alirezaghey** [SVCE-ACM/A-December-of-Algorithms-2019#19]
It would be really helpful to have some sample test cases (with correct answers) for each problem to run our solutions against.
I'm ready to create some test cases for the problems and make PRs if this aligns with your presentation guidelines.

Thanks!

**Comment by mahavisvanathan** [comment]
Since this is a community event and not a competitive programming competition we felt like an explanation of the problem and a sample would be enough. But taking into account your view, we will definitely include more test cases for the upcoming questions and you are free to send a pull request with test cases for the existing ones. How many test cases per question do you have in mind?

**Comment by alirezaghey** [comment]
Between five to ten, maybe?
IMHO, we don't need to cover every edge case, or large inputs, just enough test cases to help better understand the problem, and make sure one has a basic correct algorithm.

**Comment by cwilby** [comment]
I've written the unit tests for exercises 1 and 2 in my forked repo, that covers 2/30 of Javascript, only 30 * programming languages to go!

**Comment by alirezaghey** [comment]
IMHO, we should keep the test cases language agnostic. Just simple input-output format.

**Comment by mahavisvanathan** [comment]
Yes like @alirezaghey said we would like to keep the test cases agnostic as there are too many languages that need to be covered in case of unit tests. A section in the README with test cases would be enough. Feel free to add to the section that is already present.
