### ISSUE TITLE
How can i check my solutions?

### ISSUE THREAD

**Issue by iamsaumya** [SVCE-ACM/A-December-of-Algorithms-2019#39]
Could we have some more test-cases for the problems to check the robustness of our solution, please? 

What if i have solved all the questions and some of my implementations are wrong? Will i be getting the certificate?

**Comment by iamsaumya** [comment]
Can anyone here address my issue, please?

**Comment by jyuvaraj03** [comment]
We'll try to provide more test cases in future problems. But, since the motive of this event is just to help people learn algorithms on a consistent basis, we focus on educating participants about various algorithmic concepts not the robustness of their solutions. 

If your solutions pass for the given test cases you'll be eligible for the certificate.
